### ISSUE TITLE
2. As a player, I can change the color of the ball or select a ball in a given list.

### ISSUE THREAD

**Issue by tongoclam** [Phuongtam/gitdemo#22]

**Comment by TueKhuong** [comment]
1. Tìm màu hoặc chọn bóng đã cho trong danh sách: 5p
2. Lựa chọn màu hoặc bóng đã cho trong danh sách: 1p
3. Tìm hiểu phương pháp thực hiện: 180p
4. Thêm thay đổi trong source code: 120p
5. Chạy chương trình sau khi đã thay đổi: 5p

Tổng: 311p
