### ISSUE TITLE
9. [*] When the game is playing, a random plus or minus sign will appear on screen every 5-15 seconds, if a ball hits this sign, last player hit the ball will have 25% increase or decrease in paddle size.

### ISSUE THREAD

**Issue by tongoclam** [Phuongtam/gitdemo#30]

**Comment by trungnguyen0607** [comment]
- Tìm Icon dấu "cộng ,trừ " : 10p
- Thiết lập Icon vào chương trình : 5p
- Thiết lập random điểm rơi của Icon : 120p
- Thiết lập thời gian random từ 5-15p cho Icon : 120p
- Thiết lập khi người chơi đánh trúng Icon được cộng hoặc trừ 25% kích thước mái chèo : 120p
- Test chương trình có chứa Icon đã thực hiện : 3p
  Tổng : 378p
